DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS CONCERT_SHOWING;
DROP TABLE IF EXISTS VENUE;
DROP TABLE IF EXISTS SEAT;
DROP TABLE IF EXISTS AREA;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CASHIER;
DROP TABLE IF EXISTS SALES_LOCATION;